export const developers = [
  {
    name: "Jack Weru",
    avatar: "https://avatars.githubusercontent.com/u/97351534?v=4",
    github: "https://github.com/Jaweki",
    linked_in: "https://linkedin.com/in/jaweki-dekut",
    website: "https://portfolio.jaweki.com",
    role: "web developer",
    description:
      "Telecommunication and information Engineer. Web-frontends and backends, Network design and administration, embedded systems design, CAD (Autodesk Fusion 360). See my website for more awesome projects...",
  },
  {
    name: "Arman Jena",
    avatar: "https://avatars.githubusercontent.com/u/112967686?v=4",
    github: "https://github.com/Ajen07",
    linked_in: "https://linkedin.com/in/arman",
    website: "https://github.com/Ajen07",
    role: "web developer",
    description: "Full Stack developer | DevOps and Cloud enthusiast",
  },
  {
    name: "Shant Dashjian",
    avatar: "https://avatars.githubusercontent.com/u/2113918?v=4",
    github: "https://github.com/shantdashjian",
    linked_in: "https://www.linkedin.com/in/shantdashjian",
    website: "https://shantdashjian.com/",
    role: "web developer",
    description:
      "I bring 10 years of diverse experience in the software industry. I'm an effective problem solver, engineer, and mentor delivering solutions building full-stack web and microservices architecture based applications. I enjoy mentoring developers and teams on Test Driven Development (TDD) and Pair Programming. ",
  },
  {
    name: "Shivam",
    avatar: "https://avatars.githubusercontent.com/u/91086992?v=4",
    github: "https://github.com/shivam24161",
    linked_in: "https://linkedin.com/in/shivam",
    website: "https://github.com/shivam24161",
    role: "web developer",
    description: "Shivam has not added a description.",
  },
  {
    name: "Tanisha",
    avatar: "",
    github: "",
    linked_in: "https://linkedin.com/in/tanisha",
    website: "https://",
    role: "UI/UX designer",
    description: "Tanisha has not added a description",
  },
];

export const dinoDescription =
  "Dinosaurs, awe-inspiring giants from Earth's distant past, captivate with their colossal presence. These ancient reptiles roamed diverse ecosystems for millions of years, ranging from the towering sauropods to the swift and cunning velociraptors. Their fossilized remains unveil a world of remarkable biodiversity, revealing creatures adapted for various lifestyles, from herbivores peacefully grazing to ferocious predators hunting their prey. With their iconic appearances and mysterious extinction, dinosaurs continue to intrigue and inspire curiosity, offering glimpses into a bygone era that continues to fascinate scientists and enthusiasts alike";

export const randomFacts = [
  "The word 'dinosaur' comes from the Greek words 'deinos' meaning 'terrible' and 'sauros' meaning 'lizard.'",
  "The Tyrannosaurus rex had the strongest bite force of any land animal ever discovered, estimated to be around 8,000 pounds per square inch (psi).",
  "Velociraptors were about the size of a turkey, much smaller than the ones depicted in the Jurassic Park movies.",
  "Some dinosaurs, like the Brachiosaurus, were so large that their hearts would have weighed as much as a small car.",
  "The Stegosaurus had a brain the size of a walnut, relative to its body size.",
  "The Triceratops had the largest skull of any land animal that ever lived, measuring up to 10 feet in length.",
  "Some dinosaurs, like the Ankylosaurus, had armored plates covering their bodies for protection.",
  "The first dinosaur fossil was discovered in 1824 by Mary Ann Mantell in England.",
  "The longest dinosaur ever discovered is the Diplodocus, which measured up to 90 feet in length.",
  "Birds are considered living dinosaurs because they are descended from theropod dinosaurs like the Velociraptor and Tyrannosaurus rex.",
  "The largest dinosaur eggs ever discovered belonged to the Hypselosaurus and measured about 1.3 feet in diameter.",
  "Some dinosaurs, like the Parasaurolophus, had elaborate head crests that may have been used for communication or display.",
  "The Spinosaurus is the only known dinosaur to have spent a significant amount of time in water, leading scientists to believe it was a semi-aquatic predator.",
  "The smallest dinosaur ever discovered is the Microraptor, which was about the size of a crow.",
  "Some dinosaurs, like the Dilophosaurus, are known to have had crests on their heads, although their purpose remains uncertain.",
  "The longest recorded dinosaur footprint is over 5 feet long and was found in France.",
  "The fastest dinosaurs, like the Ornithomimus, could run at speeds of up to 40 miles per hour.",
  "The smallest dinosaur eggs ever discovered were about the size of a grape and belonged to a species of theropod dinosaur.",
  "Some dinosaurs, like the Brachiosaurus, had nostrils on the top of their heads, allowing them to breathe while partially submerged in water.",
  "The Stegosaurus had two rows of bony plates along its back, which may have been used for display or temperature regulation.",
  "The longest dinosaur name is Micropachycephalosaurus, which means 'tiny thick-headed lizard.'",
  "Some dinosaurs, like the Ankylosaurus, had clubbed tails that they used as weapons for defense.",
  "The Maiasaura was one of the few dinosaurs known to have cared for its young, as evidenced by the discovery of nests with eggs and hatchlings in close proximity.",
  "The first dinosaur to be formally named was the Megalosaurus, named in 1824 by William Buckland.",
  "Some dinosaurs, like the Spinosaurus, had conical teeth suited for catching fish, indicating a diet that included aquatic prey.",
  "The Brachiosaurus is believed to have been able to rear up on its hind legs to reach high vegetation, similar to a giraffe.",
  "The smallest known dinosaur with feathers is the Anchiornis, which lived about 160 million years ago.",
  "Some dinosaurs, like the Deinonychus, had sickle-shaped claws on their feet that they likely used to slash at prey.",
  "The heaviest dinosaur ever discovered is the Argentinosaurus, which may have weighed as much as 100 tons.",
  "Some dinosaurs, like the Velociraptor, are believed to have been highly intelligent and may have hunted in packs for increased efficiency.",
  "Dinosaurs lived on every continent on Earth.",
  "Not all dinosaurs were giants. Many were quite small, even bird-sized, and filled various ecological niches.",
  "Some dinosaurs may have had colorful feathers. Evidence from fossils suggests the presence of pigment structures in certain species.",
  "Dinosaurs likely had a complex social structure. Fossil evidence hints at herding behavior, parental care, and communication through vocalizations or displays.",
  "The extinction of dinosaurs is still debated. The most widely accepted theory involves a giant asteroid impact, but other factors might have played a role.",
  "Dinosaurs laid hard-shelled eggs in nests, similar to many reptiles and birds today.",
  "Baby dinosaurs grew quickly. They reached adult size in a relatively short period compared to other large reptiles.",
  "The environment during the dinosaur era was very different. Continents were positioned differently, and the climate was warmer and more humid globally.",
  "Many dinosaur fossils are incomplete. Paleontologists often have to piece together information from fragmentary remains to reconstruct entire creatures.",
  "The study of dinosaurs is constantly evolving. New discoveries and advancements in technology are leading to a better understanding of these prehistoric animals.",
  "Some dinosaurs may have had good senses of smell. Enlarged olfactory cavities in certain skulls suggest this possibility.",
  "Dinosaurs likely had varied metabolisms. Some might have been warm-blooded, while others were more reptilian in their body temperature regulation.",
  "The first dinosaur discoveries were mistaken for giant humans or mythical creatures. It took time for scientists to understand their true nature.",
  "Dinosaur footprints, feathers, and even stomach contents have been fossilized. These provide valuable clues about their behavior and diet.",
  "Many dinosaur names are difficult to pronounce. They come from a combination of Greek and Latin, reflecting their scientific classification.",
  "Paleontologists use a variety of techniques to study dinosaurs. These include bone analysis, computer modeling, and comparisons with living animals.",
  "Dinosaurs are a popular subject in popular culture. They appear in movies, books, toys, and even theme parks, sparking imaginations worldwide.",
  "The extinction of dinosaurs opened the way for the rise of mammals. With dinosaurs gone, mammals were able to diversify and evolve into the dominant land animals we see today.",
  "There are many ongoing dinosaur digs around the world. Paleontologists are constantly searching for new fossils to learn more about these fascinating creatures.",
  "Studying dinosaurs helps us understand the history of life on Earth. It provides insights into past ecosystems, climate change, and the processes of evolution.",
  "Amateur fossil hunters can play a role in dinosaur discoveries. Many important finds have been made by people outside the paleontological field.",
  "Museums around the world house dinosaur fossils. These collections allow people to see these amazing creatures firsthand and learn more about them.",
  "There are ethical considerations in dinosaur research. Preserving fossil sites and respecting cultural heritage are important aspects of paleontology.",
  "The study of dinosaurs is a global endeavor. Paleontologists from all over the world collaborate to share knowledge and make new discoveries.",
  "Dinosaurs continue to capture our imagination. Their size, diversity, and mysterious extinction make them a source of wonder and fascination.",
  "Paleontologists use nicknames for some dinosaurs. These informal names can be more memorable than the scientific designations.",
  "There are many unanswered questions about dinosaurs. We may never know everything about their behavior, vocalizations, or exact appearance.",
  "New dinosaur species are still being discovered. As paleontological research continues, our understanding of these creatures keeps growing.",
  "The study of dinosaurs can inspire future generations of scientists. It shows how curiosity and exploration can lead to groundbreaking discoveries.",
  "Dinosaurs are a reminder of the vastness of time. Their existence spanned millions of years, and their legacy continues to influence us today.",
];
