export const developers = [
  {
    name: "Jack Weru",
    avatar: "https://avatars.githubusercontent.com/u/97351534?v=4",
    github: "https://github.com/Jaweki",
    role: "web developer",
  },
  {
    name: "Shivam",
    avatar: "",
    github: "",
    role: "web developer",
  },
  {
    name: "Tanisha",
    avatar: "",
    github: "",
    role: "UI/UX designer",
  },
  {
    name: "Arman Jena",
    avatar: "",
    github: "",
    role: "web developer",
  },
  {
    name: "Shant Dashian",
    avatar: "",
    github: "",
    role: "scrum master",
  },
];

export const dinoDescription =
  "Dinosaurs, awe-inspiring giants from Earth's distant past, captivate with their colossal presence. These ancient reptiles roamed diverse ecosystems for millions of years, ranging from the towering sauropods to the swift and cunning velociraptors. Their fossilized remains unveil a world of remarkable biodiversity, revealing creatures adapted for various lifestyles, from herbivores peacefully grazing to ferocious predators hunting their prey. With their iconic appearances and mysterious extinction, dinosaurs continue to intrigue and inspire curiosity, offering glimpses into a bygone era that continues to fascinate scientists and enthusiasts alike";

export const filterCountries = [
  "South Africa",
  "Argentina",
  "USA",
  "Mongolia",
  "Canada, USA",
  "Egypt",
  "Niger",
  "China",
  "Canada",
  "China, Mongolia",
  "Portugal, USA",
  "France",
  "Argentina, Chile, Uruguay",
  "Spain",
  "Kazakhstan",
  "Germany",
  "China, Uzbekistan",
  "Australia",
  "India",
  "Tanzania, USA",
  "England, Spain, United Kingdom",
  "England, United Kingdom",
  "Algeria, Portugal, Tanzania, USA",
  "England, United Kingdom, USA",
  "Algeria, Egypt, Morocco, North Africa",
  "South Africa, USA, Zimbabwe",
  "France, Germany",
  "Antarctica",
  "England, France, Portugal, United Kingdom",
  "Morocco",
  "Tanzania",
  "Japan",
  "Brazil",
  "Lesotho, South Africa",
  "Belgium, England, United Kingdom",
  "Argentina, USA",
  "Madagascar",
  "Lesotho",
  "Romania",
  "Malawi",
  "Lesotho, South Africa, Zimbabwe",
  "Algeria, Niger, Tunisia",
  "Russia",
  "United Kingdom, Wales",
  "France, Germany, Switzerland",
  "China, Mongolia, Russia",
  "France, Spain",
  "Austria, France, Romania, Spain",
  "Canada, Mongolia",
  "Egypt, Morocco",
  "France, Romania, Spain",
  "Uzbekistan",
  "England, Niger, Romania, United Kingdom",
  "Zimbabwe",
];
